-- MySQL Script generated by MySQL Workbench
-- Sat Oct 26 03:49:59 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema virtuallearning
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema virtuallearning
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `virtuallearning` DEFAULT CHARACTER SET utf8 ;
USE `virtuallearning` ;

-- -----------------------------------------------------
-- Table `virtuallearning`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `virtuallearning`.`users` (
  `usuario_id` VARCHAR(12) NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `correo` VARCHAR(45) NULL,
  `pass` TINYTEXT NULL,
  `usuario` VARCHAR(45) NULL,
  `carnet` VARCHAR(8) NULL,
  `foto` TINYTEXT NULL,
  `slack` VARCHAR(45) NULL,
  `groups` TINYTEXT NULL,
  `facultad` VARCHAR(70) NULL,
  `inicio` DATETIME NULL,
  `fin` DATETIME NULL,
  `token` VARCHAR(20) NULL,
  `rol` INT NULL,
  `estado` TINYINT NULL,
  PRIMARY KEY (`usuario_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `virtuallearning`.`activity_register`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `virtuallearning`.`activity_register` (
  `activity_id` VARCHAR(12) NOT NULL,
  `tipo` INT NULL,
  `fecha` DATETIME NULL,
  `to` VARCHAR(12) NULL,
  `from` VARCHAR(12) NULL,
  PRIMARY KEY (`activity_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
